def _sdk_startup_elements():
    return [
        {
            "page": "启动协议弹窗",
            "label": "拒绝",
            "resource_id": "com.xianyui.qs.cn:id/qs_base_btn_cancel",
            "text": "拒绝",
            "class_name": "android.widget.Button",
            "kind": "button",
        },
        {
            "page": "启动协议弹窗",
            "label": "同意",
            "resource_id": "com.xianyui.qs.cn:id/btn_confirm",
            "text": "同意",
            "class_name": "android.widget.Button",
            "kind": "button",
        },
        {
            "page": "启动协议弹窗",
            "label": "用户服务协议",
            "resource_id": "",
            "text": "《用户服务协议》",
            "class_name": "android.widget.TextView",
            "kind": "link",
        },
        {
            "page": "启动协议弹窗",
            "label": "隐私政策",
            "resource_id": "",
            "text": "《隐私政策》",
            "class_name": "android.widget.TextView",
            "kind": "link",
        },
        {
            "page": "启动协议弹窗",
            "label": "通知授权",
            "resource_id": "",
            "text": "《通知授权》",
            "class_name": "android.widget.TextView",
            "kind": "link",
        },
    ]


def _sdk_login_standard_template_sections():
    return [
        {
            "title": "启动协议确认",
            "summary": "先处理首次启动时的协议弹窗，确保后续资源加载不被拦截。",
            "goal": "点击同意后进入资源加载阶段。",
            "controls": ["同意", "拒绝", "用户服务协议", "隐私政策", "通知授权"],
            "steps": ["等待启动协议弹窗", "点击启动协议同意"],
        },
        {
            "title": "账号登录入口切换",
            "summary": "资源加载结束后，检查登录页并切换到账号密码模式。",
            "goal": "确认登录入口和主要控件存在，然后切换到账号登录。",
            "controls": ["账号密码登录切换", "本机号码", "获取验证码", "登录游戏", "勾选协议"],
            "steps": ["等待 SDK 登录弹窗出现", "校验手机号登录页元素", "点击账号登录入口", "等待账号密码表单出现"],
        },
        {
            "title": "账号登录主流程",
            "summary": "以标准账号完成协议勾选、账号输入、密码输入与提交。",
            "goal": "输入账号密码并进入游戏主界面。",
            "controls": ["账号输入框", "密码输入框", "忘记密码", "登录游戏", "关闭弹窗"],
            "steps": ["输入测试账号", "输入测试密码", "勾选登录协议圆圈", "点击登录游戏", "等待进入游戏界面", "保留进入游戏截图"],
        },
        {
            "title": "异常输入校验",
            "summary": "补充协议未勾选、特殊字符账号、短密码等异常场景。",
            "goal": "保留异常时的页面状态，判断 SDK 校验是否生效。",
            "controls": ["账号输入框", "密码输入框", "登录游戏", "忘记密码"],
            "steps": ["输入特殊字符账号", "输入过短密码", "未勾选协议直接点击登录", "校验仍停留在账号登录页", "保留异常输入结果截图"],
        },
    ]


def _sdk_login_elements():
    return [
        {
            "page": "SDK 手机号登录页",
            "label": "账号密码登录切换",
            "resource_id": "com.xianyui.qs.cn:id/tv_single_account_login",
            "text": "账号登录",
            "class_name": "android.widget.TextView",
            "kind": "button",
        },
        {
            "page": "SDK 手机号登录页",
            "label": "手机号输入框",
            "resource_id": "com.xianyui.qs.cn:id/et_user_phone",
            "text": "输入手机号",
            "class_name": "android.widget.EditText",
            "kind": "input",
        },
        {
            "page": "SDK 手机号登录页",
            "label": "本机号码",
            "resource_id": "com.xianyui.qs.cn:id/tv_onekey_login",
            "text": "本机号码",
            "class_name": "android.widget.TextView",
            "kind": "button",
        },
        {
            "page": "SDK 手机号登录页",
            "label": "短信验证码输入框",
            "resource_id": "com.xianyui.qs.cn:id/et_user_code",
            "text": "短信验证码",
            "class_name": "android.widget.EditText",
            "kind": "input",
        },
        {
            "page": "SDK 手机号登录页",
            "label": "获取验证码",
            "resource_id": "com.xianyui.qs.cn:id/btn_get_code",
            "text": "获取",
            "class_name": "android.widget.Button",
            "kind": "button",
        },
        {
            "page": "SDK 手机号登录页",
            "label": "登录游戏",
            "resource_id": "com.xianyui.qs.cn:id/btn_reg_compete",
            "text": "登录游戏",
            "class_name": "android.widget.Button",
            "kind": "button",
        },
        {
            "page": "SDK 手机号登录页",
            "label": "勾选协议",
            "resource_id": "com.xianyui.qs.cn:id/cb_register",
            "text": "",
            "class_name": "android.widget.CheckBox",
            "kind": "checkbox",
        },
        {
            "page": "SDK 手机号登录页",
            "label": "协议说明",
            "resource_id": "com.xianyui.qs.cn:id/tv_agree_tip",
            "text": "我已详细阅读并同意",
            "class_name": "android.widget.TextView",
            "kind": "text",
        },
        {
            "page": "SDK 手机号登录页",
            "label": "用户协议",
            "resource_id": "com.xianyui.qs.cn:id/tv_service_tip",
            "text": "《用户协议》",
            "class_name": "android.widget.TextView",
            "kind": "link",
        },
        {
            "page": "SDK 手机号登录页",
            "label": "隐私政策",
            "resource_id": "com.xianyui.qs.cn:id/tv_privacy_tip",
            "text": "《隐私政策》",
            "class_name": "android.widget.TextView",
            "kind": "link",
        },
        {
            "page": "SDK 手机号登录页",
            "label": "通知授权",
            "resource_id": "com.xianyui.qs.cn:id/tv_notification_tip",
            "text": "《通知授权》",
            "class_name": "android.widget.TextView",
            "kind": "link",
        },
        {
            "page": "SDK 账号密码页",
            "label": "账号输入框",
            "resource_id": "com.xianyui.qs.cn:id/eet_input",
            "text": "请输入账号",
            "class_name": "android.widget.EditText",
            "kind": "input",
        },
        {
            "page": "SDK 账号密码页",
            "label": "密码输入框",
            "resource_id": "com.xianyui.qs.cn:id/eet_input",
            "text": "请输入密码6–22位",
            "class_name": "android.widget.EditText",
            "kind": "input",
        },
        {
            "page": "SDK 账号密码页",
            "label": "忘记密码",
            "resource_id": "com.xianyui.qs.cn:id/tv_single_fofget_pwd",
            "text": "忘记密码",
            "class_name": "android.widget.TextView",
            "kind": "button",
        },
        {
            "page": "SDK 账号密码页",
            "label": "登录游戏",
            "resource_id": "com.xianyui.qs.cn:id/reg_compete_btn",
            "text": "登录游戏",
            "class_name": "android.widget.Button",
            "kind": "button",
        },
        {
            "page": "SDK 账号密码页",
            "label": "账号登录切回",
            "resource_id": "com.xianyui.qs.cn:id/tv_single_account_login",
            "text": "账号登录",
            "class_name": "android.widget.TextView",
            "kind": "button",
        },
        {
            "page": "SDK 账号密码页",
            "label": "关闭弹窗",
            "resource_id": "com.xianyui.qs.cn:id/close_btn",
            "text": "",
            "class_name": "android.widget.RelativeLayout",
            "kind": "button",
        },
    ]


def _launch_steps():
    return [
        {
            "step_name": "等待启动协议弹窗",
            "step_type": "wait_image",
            "selector_type": "image",
            "selector_value": "xianyu/sdk_agree_confirm.png",
            "wait_timeout_sec": 8,
            "continue_on_failure": True,
            "capture_on_success": True,
            "remark": "确认游戏启动后先进入隐私协议弹窗。",
        },
        {
            "step_name": "点击启动协议同意",
            "step_type": "tap_image",
            "selector_type": "image",
            "selector_value": "xianyu/sdk_agree_confirm.png",
            "wait_timeout_sec": 8,
            "continue_on_failure": True,
            "capture_on_success": True,
            "remark": "同意启动协议，继续资源加载。",
        },
        {
            "step_name": "检测已登录状态并进入 SDK",
            "step_type": "ensure_xianyu_account_login",
            "selector_type": "none",
            "selector_value": "",
            "wait_timeout_sec": 900,
            "capture_on_success": True,
            "remark": "已登录则通过左侧悬浮窗进入用户中心并切换账号，新安装则直接继续登录。",
        },
    ]


def _switch_account_steps():
    return _launch_steps() + [
        {
            "step_name": "校验手机号登录页元素",
            "step_type": "assert_image_exists",
            "selector_type": "image",
            "selector_value": "xianyu/sdk_login_button.png",
            "wait_timeout_sec": 20,
            "capture_on_success": True,
            "remark": "确认默认展示手机号快捷登录页。",
        },
        {
            "step_name": "点击账号登录入口",
            "step_type": "tap_image",
            "selector_type": "image",
            "selector_value": "xianyu/sdk_account_login_switch.png",
            "wait_timeout_sec": 20,
            "capture_on_success": True,
            "remark": "切换到账号密码登录表单。",
        },
        {
            "step_name": "等待账号密码表单出现",
            "step_type": "wait_image",
            "selector_type": "image",
            "selector_value": "xianyu/sdk_username_field.png",
            "wait_timeout_sec": 30,
            "capture_on_success": True,
            "remark": "确认账号密码登录页已经展示。",
        },
        {
            "step_name": "校验账号输入框",
            "step_type": "assert_image_exists",
            "selector_type": "image",
            "selector_value": "xianyu/sdk_username_field.png",
            "wait_timeout_sec": 15,
            "capture_on_success": True,
            "remark": "账号登录页需要展示账号输入框。",
        },
        {
            "step_name": "保留账号登录页截图",
            "step_type": "screenshot",
            "selector_type": "none",
            "selector_value": "",
            "wait_timeout_sec": 5,
            "capture_on_success": True,
            "remark": "沉淀账号密码登录表单截图，便于后续对比 SDK UI 变化。",
        },
    ]


def _sdk_account_password_steps(
    account_value="zsr005",
    password_value="123456",
    include_checkbox=True,
    verify_entry=True,
):
    steps = [
        {
            "step_name": "输入测试账号",
            "step_type": "input_text",
            "selector_type": "image",
            "selector_value": "xianyu/sdk_username_field.png",
            "input_value": account_value,
            "wait_timeout_sec": 20,
            "capture_on_success": True,
            "remark": "账号输入框按图片定位后输入测试账号。",
        },
        {
            "step_name": "输入测试密码",
            "step_type": "input_text",
            "selector_type": "image",
            "selector_value": "xianyu/sdk_password_field.png",
            "input_value": password_value,
            "wait_timeout_sec": 20,
            "capture_on_success": True,
            "remark": "密码输入框按图片定位后输入测试密码。",
        },
    ]
    if include_checkbox:
        steps.append(
            {
                "step_name": "勾选登录协议圆圈",
                "step_type": "tap_image",
                "selector_type": "image",
                "selector_value": "xianyu/sdk_agreement_circle.png",
                "wait_timeout_sec": 20,
                "capture_on_success": True,
                "remark": "点击协议圆圈完成协议勾选。",
            }
        )
    steps.append(
        {
            "step_name": "点击登录游戏",
            "step_type": "tap_image",
            "selector_type": "image",
            "selector_value": "xianyu/sdk_login_button.png",
            "wait_timeout_sec": 20,
            "capture_on_success": True,
            "remark": "提交账号密码登录。",
        }
    )
    if verify_entry:
        steps.append(
            {
                "step_name": "处理登录后协议并再次点击登录",
                "step_type": "handle_xianyu_post_login_consent",
                "selector_type": "image",
                "selector_value": "xianyu/sdk_post_login_agree.png",
                "wait_timeout_sec": 15,
                "capture_on_success": True,
                "remark": "如果出现登录后协议弹窗，点击同意并根据返回的账号页再次点击登录游戏。",
            }
        )
        steps.extend(
            [
                {
                    "step_name": "等待进入游戏界面",
                    "step_type": "wait_image",
                    "selector_type": "image",
                    "selector_value": "xianyu/xianyu_floating_entry.png",
                    "wait_timeout_sec": 90,
                    "capture_on_success": True,
                    "remark": "进入游戏后通常会出现左侧悬浮窗入口。",
                },
                {
                    "step_name": "保留进入游戏截图",
                    "step_type": "screenshot",
                    "selector_type": "none",
                    "selector_value": "",
                    "wait_timeout_sec": 5,
                    "capture_on_success": True,
                    "remark": "沉淀进入游戏后的凭证截图。",
                },
            ]
        )
    return steps


def _sdk_floating_panel_elements():
    return [
        {
            "page": "游戏内悬浮窗",
            "label": "悬浮窗入口",
            "resource_id": "",
            "text": "",
            "class_name": "android.widget.ImageView",
            "kind": "button",
        },
        {
            "page": "用户中心面板",
            "label": "关闭弹窗",
            "resource_id": "",
            "text": "",
            "class_name": "android.widget.ImageView",
            "kind": "button",
        },
        {
            "page": "用户中心面板",
            "label": "切换账号",
            "resource_id": "",
            "text": "切换账号",
            "class_name": "android.widget.Button",
            "kind": "button",
        },
        {
            "page": "用户中心面板",
            "label": "账号管理",
            "resource_id": "",
            "text": "账号管理",
            "class_name": "android.widget.TextView",
            "kind": "button",
        },
        {
            "page": "用户中心面板",
            "label": "客服",
            "resource_id": "",
            "text": "客服",
            "class_name": "android.widget.TextView",
            "kind": "button",
        },
        {
            "page": "用户中心面板",
            "label": "用户协议",
            "resource_id": "",
            "text": "用户协议",
            "class_name": "android.widget.TextView",
            "kind": "link",
        },
        {
            "page": "用户中心面板",
            "label": "隐私政策",
            "resource_id": "",
            "text": "隐私政策",
            "class_name": "android.widget.TextView",
            "kind": "link",
        },
        {
            "page": "用户中心面板",
            "label": "订单列表",
            "resource_id": "",
            "text": "订单列表",
            "class_name": "android.widget.TextView",
            "kind": "button",
        },
        {
            "page": "用户中心面板",
            "label": "加速",
            "resource_id": "",
            "text": "加速",
            "class_name": "android.widget.TextView",
            "kind": "button",
        },
        {
            "page": "游戏主界面",
            "label": "左侧悬浮入口",
            "resource_id": "",
            "text": "",
            "class_name": "android.widget.ImageView",
            "kind": "button",
        },
    ]


def _sdk_account_management_elements():
    return [
        {
            "page": "账号管理页",
            "label": "页面标题",
            "resource_id": "",
            "text": "账号管理",
            "class_name": "android.widget.TextView",
            "kind": "text",
        },
        {
            "page": "账号管理页",
            "label": "刷新",
            "resource_id": "",
            "text": "",
            "class_name": "android.widget.ImageView",
            "kind": "button",
        },
        {
            "page": "账号管理页",
            "label": "关闭",
            "resource_id": "",
            "text": "",
            "class_name": "android.widget.ImageView",
            "kind": "button",
        },
        {
            "page": "账号管理页",
            "label": "修改密码",
            "resource_id": "",
            "text": "修改密码",
            "class_name": "android.widget.TextView",
            "kind": "button",
        },
        {
            "page": "账号管理页",
            "label": "取消授权",
            "resource_id": "",
            "text": "取消授权",
            "class_name": "android.widget.TextView",
            "kind": "button",
        },
        {
            "page": "账号管理页",
            "label": "账号注销",
            "resource_id": "",
            "text": "账号注销",
            "class_name": "android.widget.TextView",
            "kind": "button",
        },
        {
            "page": "账号管理页",
            "label": "手机号",
            "resource_id": "",
            "text": "手机号",
            "class_name": "android.widget.TextView",
            "kind": "button",
        },
        {
            "page": "账号管理页",
            "label": "实名信息",
            "resource_id": "",
            "text": "实名信息",
            "class_name": "android.widget.TextView",
            "kind": "button",
        },
        {
            "page": "账号管理页",
            "label": "第三方SDK目录",
            "resource_id": "",
            "text": "第三方SDK目录",
            "class_name": "android.widget.TextView",
            "kind": "button",
        },
    ]


def get_android_ui_flow_presets():
    start_elements = _sdk_startup_elements()
    login_elements = _sdk_login_elements()
    floating_panel_elements = _sdk_floating_panel_elements()
    account_management_elements = _sdk_account_management_elements()
    return [
        {
            "key": "xianyu_leyuan_account_management_page",
            "name": "仙遇-用户中心账号管理页",
            "summary": "覆盖用户中心里的账号管理页，整理修改密码、取消授权、账号注销、手机号、实名信息、第三方SDK目录等按钮，并补充刷新与关闭入口。",
            "ui_elements": account_management_elements,
            "template_sections": [
                {
                    "title": "页面打开",
                    "summary": "从用户中心进入账号管理页后，先确认标题和关闭/刷新入口存在。",
                    "goal": "账号管理页成功打开。",
                    "controls": ["页面标题", "刷新", "关闭"],
                    "steps": ["点击账号管理", "校验账号管理页出现"],
                },
                {
                    "title": "账号安全相关",
                    "summary": "修改密码和账号注销属于高风险入口，适合单独验证是否能正常打开对应页或弹窗。",
                    "goal": "账号安全相关入口均可点击。",
                    "controls": ["修改密码", "取消授权", "账号注销"],
                    "steps": [
                        "点击修改密码",
                        "校验修改密码页或弹窗出现",
                        "返回账号管理页",
                        "点击取消授权",
                        "校验取消授权页或弹窗出现",
                        "返回账号管理页",
                        "点击账号注销",
                        "校验账号注销确认页或弹窗出现",
                    ],
                },
                {
                    "title": "绑定信息相关",
                    "summary": "手机号、实名信息通常用于查看或跳转信息页，适合检查页面跳转和返回逻辑。",
                    "goal": "手机号和实名信息可单独进入。",
                    "controls": ["手机号", "实名信息"],
                    "steps": ["点击手机号", "校验手机号详情页出现", "返回账号管理页", "点击实名信息", "校验实名信息页出现"],
                },
                {
                    "title": "第三方信息",
                    "summary": "第三方SDK目录通常是一个说明页，可作为合规信息检查项。",
                    "goal": "第三方SDK目录可打开。",
                    "controls": ["第三方SDK目录"],
                    "steps": ["点击第三方SDK目录", "校验目录页出现", "返回账号管理页", "点击关闭"],
                },
            ],
            "steps": [
                {
                    "step_name": "点击账号管理",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "账号管理",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "从用户中心进入账号管理页。",
                },
                {
                    "step_name": "校验账号管理页出现",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "账号管理",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "确认标题和页面加载完成。",
                },
                {
                    "step_name": "点击修改密码",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "修改密码",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "验证修改密码入口。",
                },
                {
                    "step_name": "校验修改密码页出现",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "修改密码",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "修改密码页或弹窗出现。",
                },
                {
                    "step_name": "返回账号管理页",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "账号管理",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "回到账号管理页继续测试其他入口。",
                },
                {
                    "step_name": "点击取消授权",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "取消授权",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "验证取消授权入口。",
                },
                {
                    "step_name": "校验取消授权页出现",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "取消授权",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "取消授权页或弹窗出现。",
                },
                {
                    "step_name": "返回账号管理页",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "账号管理",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "回到账号管理页继续测试账号注销入口。",
                },
                {
                    "step_name": "点击账号注销",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "账号注销",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "验证账号注销入口。",
                },
                {
                    "step_name": "校验账号注销确认页出现",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "账号注销",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "账号注销确认页或弹窗出现。",
                },
                {
                    "step_name": "返回账号管理页",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "账号管理",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "继续测试信息类入口。",
                },
                {
                    "step_name": "点击手机号",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "手机号",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "验证手机号入口。",
                },
                {
                    "step_name": "校验手机号详情页出现",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "手机号",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "手机号详情页或弹窗出现。",
                },
                {
                    "step_name": "返回账号管理页",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "账号管理",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "继续测试实名信息。",
                },
                {
                    "step_name": "点击实名信息",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "实名信息",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "验证实名信息入口。",
                },
                {
                    "step_name": "校验实名信息页出现",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "实名信息",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "实名信息页或弹窗出现。",
                },
                {
                    "step_name": "返回账号管理页",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "账号管理",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "继续测试第三方 SDK 目录。",
                },
                {
                    "step_name": "点击第三方SDK目录",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "第三方SDK目录",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "验证第三方 SDK 目录入口。",
                },
                {
                    "step_name": "校验目录页出现",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "第三方SDK目录",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "目录页或弹窗出现。",
                },
                {
                    "step_name": "返回账号管理页",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "账号管理",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "最后回到账号管理页准备关闭。",
                },
                {
                    "step_name": "点击刷新",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "刷新账号管理页，确认页面不会异常退出。",
                },
                {
                    "step_name": "点击关闭",
                    "step_type": "tap_image",
                    "selector_type": "image",
                    "selector_value": "xianyu/xianyu_user_center_close.png",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "通过右上角关闭按钮模板结束账号管理分支。",
                },
            ],
        },
        {
            "key": "xianyu_leyuan_change_password_page",
            "name": "仙遇-账号管理-修改密码页",
            "summary": "覆盖账号管理里的修改密码页面，整理短信验证码、新密码、确认密码、获取验证码和完成按钮等实际元素。",
            "ui_elements": [
                {
                    "page": "修改密码页",
                    "label": "页面标题",
                    "resource_id": "com.xianyui.qs.cn:id/tv_title",
                    "text": "修改密码",
                    "class_name": "android.widget.TextView",
                    "kind": "text",
                },
                {
                    "page": "修改密码页",
                    "label": "返回",
                    "resource_id": "com.xianyui.qs.cn:id/iv_back_view",
                    "text": "",
                    "class_name": "android.widget.ImageView",
                    "kind": "button",
                },
                {
                    "page": "修改密码页",
                    "label": "刷新",
                    "resource_id": "com.xianyui.qs.cn:id/iv_refresh_view",
                    "text": "",
                    "class_name": "android.widget.ImageView",
                    "kind": "button",
                },
                {
                    "page": "修改密码页",
                    "label": "关闭",
                    "resource_id": "com.xianyui.qs.cn:id/iv_close_view",
                    "text": "",
                    "class_name": "android.widget.ImageView",
                    "kind": "button",
                },
                {
                    "page": "修改密码页",
                    "label": "短信提示",
                    "resource_id": "",
                    "text": "短信将发送到手机188****9917",
                    "class_name": "android.widget.TextView",
                    "kind": "text",
                },
                {
                    "page": "修改密码页",
                    "label": "短信验证码输入框",
                    "resource_id": "",
                    "text": "请填写短信验证码",
                    "class_name": "android.widget.EditText",
                    "kind": "input",
                },
                {
                    "page": "修改密码页",
                    "label": "获取验证码",
                    "resource_id": "",
                    "text": "获取验证码",
                    "class_name": "android.widget.Button",
                    "kind": "button",
                },
                {
                    "page": "修改密码页",
                    "label": "新密码输入框",
                    "resource_id": "",
                    "text": "请填写新密码6-22位",
                    "class_name": "android.widget.EditText",
                    "kind": "input",
                },
                {
                    "page": "修改密码页",
                    "label": "确认新密码输入框",
                    "resource_id": "",
                    "text": "请确认新密码",
                    "class_name": "android.widget.EditText",
                    "kind": "input",
                },
                {
                    "page": "修改密码页",
                    "label": "完成",
                    "resource_id": "",
                    "text": "完成",
                    "class_name": "android.widget.Button",
                    "kind": "button",
                },
            ],
            "template_sections": [
                {
                    "title": "页面打开",
                    "summary": "修改密码页依赖账号绑定手机号发送验证码，进入后先检查标题和顶部工具按钮。",
                    "goal": "修改密码页成功打开。",
                    "controls": ["页面标题", "返回", "刷新", "关闭"],
                    "steps": ["点击修改密码", "校验修改密码页出现"],
                },
                {
                    "title": "验证码与新密码",
                    "summary": "页面包含短信验证码、新密码和确认密码三段输入区，适合继续补输入和长度校验。",
                    "goal": "关键输入框与提交按钮都可见。",
                    "controls": ["短信验证码输入框", "获取验证码", "新密码输入框", "确认新密码输入框", "完成"],
                    "steps": ["校验短信验证码输入框", "校验新密码输入框", "校验确认新密码输入框", "校验完成按钮"],
                },
                {
                    "title": "返回与关闭",
                    "summary": "修改密码页是可返回的 WebView 页面，保留返回和关闭入口便于脚本恢复现场。",
                    "goal": "修改密码页可安全回退。",
                    "controls": ["返回", "关闭"],
                    "steps": ["点击返回", "返回账号管理页"],
                },
            ],
            "steps": [
                {
                    "step_name": "点击修改密码",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "修改密码",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "从账号管理页进入修改密码页。",
                },
                {
                    "step_name": "校验修改密码页出现",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "修改密码",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "确认标题和顶部返回/刷新/关闭入口出现。",
                },
                {
                    "step_name": "校验短信验证码输入框",
                    "step_type": "assert_exists",
                    "selector_type": "text",
                    "selector_value": "请填写短信验证码",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "确认短信验证码输入框和获取验证码按钮可见。",
                },
                {
                    "step_name": "校验新密码输入框",
                    "step_type": "assert_exists",
                    "selector_type": "text",
                    "selector_value": "请填写新密码6-22位",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "确认新密码输入框可见。",
                },
                {
                    "step_name": "校验确认新密码输入框",
                    "step_type": "assert_exists",
                    "selector_type": "text",
                    "selector_value": "请确认新密码",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "确认确认密码输入框可见。",
                },
                {
                    "step_name": "校验完成按钮",
                    "step_type": "assert_exists",
                    "selector_type": "text",
                    "selector_value": "完成",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "确认提交按钮存在。",
                },
            ],
        },
        {
            "key": "xianyu_leyuan_cancel_authorization_dialog",
            "name": "仙遇-账号管理-取消授权弹窗",
            "summary": "覆盖取消授权后的风险确认弹窗，整理确认、返回和阅读同意勾选框等元素。",
            "ui_elements": [
                {
                    "page": "取消授权弹窗",
                    "label": "页面标题",
                    "resource_id": "",
                    "text": "温馨提示",
                    "class_name": "android.widget.TextView",
                    "kind": "text",
                },
                {
                    "page": "取消授权弹窗",
                    "label": "风险说明",
                    "resource_id": "",
                    "text": "取消授权后，所属的所有隐私信息将无法恢复",
                    "class_name": "android.widget.TextView",
                    "kind": "text",
                },
                {
                    "page": "取消授权弹窗",
                    "label": "协议勾选框",
                    "resource_id": "",
                    "text": "我已阅读同意以上协议",
                    "class_name": "android.widget.CheckBox",
                    "kind": "checkbox",
                },
                {
                    "page": "取消授权弹窗",
                    "label": "返回",
                    "resource_id": "",
                    "text": "返回",
                    "class_name": "android.widget.Button",
                    "kind": "button",
                },
                {
                    "page": "取消授权弹窗",
                    "label": "确认",
                    "resource_id": "",
                    "text": "确认",
                    "class_name": "android.widget.Button",
                    "kind": "button",
                },
            ],
            "template_sections": [
                {
                    "title": "弹窗确认",
                    "summary": "取消授权会触发风险说明弹窗，先确认标题、返回和确认按钮都存在。",
                    "goal": "取消授权确认弹窗成功打开。",
                    "controls": ["温馨提示", "返回", "确认"],
                    "steps": ["点击取消授权", "校验取消授权确认弹窗出现"],
                },
                {
                    "title": "协议勾选",
                    "summary": "弹窗包含必须阅读同意的勾选项，适合补充二次确认与按钮可用状态。",
                    "goal": "勾选后可继续确认。",
                    "controls": ["我已阅读同意以上协议"],
                    "steps": ["勾选协议", "校验确认按钮可点击"],
                },
                {
                    "title": "返回现场",
                    "summary": "保留返回操作，确保脚本不会在高风险弹窗里卡住。",
                    "goal": "可安全回到账号管理页。",
                    "controls": ["返回"],
                    "steps": ["点击返回", "返回账号管理页"],
                },
            ],
            "steps": [
                {
                    "step_name": "点击取消授权",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "取消授权",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "从账号管理页进入取消授权确认弹窗。",
                },
                {
                    "step_name": "校验取消授权确认弹窗出现",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "温馨提示",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "确认风险说明弹窗已出现。",
                },
                {
                    "step_name": "勾选协议",
                    "step_type": "tap_left_of_text",
                    "selector_type": "text",
                    "selector_value": "我已阅读同意以上协议",
                    "input_value": "26",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "点击协议文字左侧圆圈。",
                },
                {
                    "step_name": "校验确认按钮可点击",
                    "step_type": "assert_exists",
                    "selector_type": "text",
                    "selector_value": "确认",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "确认按钮在勾选后应保持可交互。",
                },
            ],
        },
        {
            "key": "xianyu_leyuan_account_cancellation_page",
            "name": "仙遇-账号管理-账号注销页",
            "summary": "覆盖账号注销确认页，整理勾选框、返回和确认按钮，以及页面中的条件说明文本。",
            "ui_elements": [
                {
                    "page": "账号注销页",
                    "label": "页面标题",
                    "resource_id": "com.xianyui.qs.cn:id/tv_title",
                    "text": "账号注销",
                    "class_name": "android.widget.TextView",
                    "kind": "text",
                },
                {
                    "page": "账号注销页",
                    "label": "返回",
                    "resource_id": "com.xianyui.qs.cn:id/iv_back_view",
                    "text": "",
                    "class_name": "android.widget.ImageView",
                    "kind": "button",
                },
                {
                    "page": "账号注销页",
                    "label": "刷新",
                    "resource_id": "com.xianyui.qs.cn:id/iv_refresh_view",
                    "text": "",
                    "class_name": "android.widget.ImageView",
                    "kind": "button",
                },
                {
                    "page": "账号注销页",
                    "label": "关闭",
                    "resource_id": "com.xianyui.qs.cn:id/iv_close_view",
                    "text": "",
                    "class_name": "android.widget.ImageView",
                    "kind": "button",
                },
                {
                    "page": "账号注销页",
                    "label": "协议勾选框",
                    "resource_id": "",
                    "text": "我已阅读同意以上协议",
                    "class_name": "android.widget.CheckBox",
                    "kind": "checkbox",
                },
                {
                    "page": "账号注销页",
                    "label": "返回",
                    "resource_id": "",
                    "text": "返回",
                    "class_name": "android.widget.Button",
                    "kind": "button",
                },
                {
                    "page": "账号注销页",
                    "label": "确认",
                    "resource_id": "",
                    "text": "确认",
                    "class_name": "android.widget.Button",
                    "kind": "button",
                },
            ],
            "template_sections": [
                {
                    "title": "注销条件",
                    "summary": "页面先列出账号注销的前置条件和风险提示，适合做页面冒烟确认。",
                    "goal": "账号注销页完整打开。",
                    "controls": ["返回", "刷新", "关闭"],
                    "steps": ["点击账号注销", "校验账号注销页出现"],
                },
                {
                    "title": "协议与确认",
                    "summary": "页面底部带协议勾选框和确认按钮，勾选前后状态值得单独验证。",
                    "goal": "勾选后可继续注销确认。",
                    "controls": ["我已阅读同意以上协议", "确认"],
                    "steps": ["勾选协议", "校验确认按钮可点击"],
                },
                {
                    "title": "返回恢复",
                    "summary": "保留返回按钮，方便测试完成后恢复到账号管理页。",
                    "goal": "账号注销页可安全回退。",
                    "controls": ["返回"],
                    "steps": ["点击返回", "返回账号管理页"],
                },
            ],
            "steps": [
                {
                    "step_name": "点击账号注销",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "账号注销",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "从账号管理页进入账号注销页。",
                },
                {
                    "step_name": "校验账号注销页出现",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "账号注销",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "确认注销页标题和正文条件可见。",
                },
                {
                    "step_name": "勾选协议",
                    "step_type": "tap_left_of_text",
                    "selector_type": "text",
                    "selector_value": "我已阅读同意以上协议",
                    "input_value": "26",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "点击协议文字左侧圆圈。",
                },
                {
                    "step_name": "校验确认按钮可点击",
                    "step_type": "assert_exists",
                    "selector_type": "text",
                    "selector_value": "确认",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "确认按钮在勾选后应保持可交互。",
                },
            ],
        },
        {
            "key": "xianyu_leyuan_phone_bound_page",
            "name": "仙遇-账号管理-手机号已绑定页",
            "summary": "覆盖手机号入口后的绑定信息页，整理绑定手机号和更换手机号码按钮。",
            "ui_elements": [
                {
                    "page": "手机号已绑定页",
                    "label": "页面标题",
                    "resource_id": "com.xianyui.qs.cn:id/tv_title",
                    "text": "手机号已绑定",
                    "class_name": "android.widget.TextView",
                    "kind": "text",
                },
                {
                    "page": "手机号已绑定页",
                    "label": "返回",
                    "resource_id": "com.xianyui.qs.cn:id/iv_back_view",
                    "text": "",
                    "class_name": "android.widget.ImageView",
                    "kind": "button",
                },
                {
                    "page": "手机号已绑定页",
                    "label": "刷新",
                    "resource_id": "com.xianyui.qs.cn:id/iv_refresh_view",
                    "text": "",
                    "class_name": "android.widget.ImageView",
                    "kind": "button",
                },
                {
                    "page": "手机号已绑定页",
                    "label": "关闭",
                    "resource_id": "com.xianyui.qs.cn:id/iv_close_view",
                    "text": "",
                    "class_name": "android.widget.ImageView",
                    "kind": "button",
                },
                {
                    "page": "手机号已绑定页",
                    "label": "区号",
                    "resource_id": "",
                    "text": "+86",
                    "class_name": "android.widget.TextView",
                    "kind": "text",
                },
                {
                    "page": "手机号已绑定页",
                    "label": "已绑定手机号",
                    "resource_id": "",
                    "text": "188****9917",
                    "class_name": "android.widget.TextView",
                    "kind": "text",
                },
                {
                    "page": "手机号已绑定页",
                    "label": "更换手机号码",
                    "resource_id": "",
                    "text": "更换手机号码",
                    "class_name": "android.widget.Button",
                    "kind": "button",
                },
            ],
            "template_sections": [
                {
                    "title": "绑定展示",
                    "summary": "页面只展示当前绑定手机号和国家区号，适合校验脱敏展示是否正确。",
                    "goal": "手机号绑定信息完整显示。",
                    "controls": ["+86", "188****9917"],
                    "steps": ["点击手机号", "校验手机号已绑定页出现"],
                },
                {
                    "title": "更换入口",
                    "summary": "页面核心操作是更换手机号码按钮，后续可继续补换绑流程。",
                    "goal": "更换手机号码入口可点击。",
                    "controls": ["更换手机号码"],
                    "steps": ["校验更换手机号码按钮"],
                },
                {
                    "title": "返回恢复",
                    "summary": "保留返回、刷新和关闭入口，方便脚本回到账号管理页。",
                    "goal": "手机号页可安全回退。",
                    "controls": ["返回", "刷新", "关闭"],
                    "steps": ["点击返回", "返回账号管理页"],
                },
            ],
            "steps": [
                {
                    "step_name": "点击手机号",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "手机号",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "从账号管理页进入手机号绑定页。",
                },
                {
                    "step_name": "校验手机号已绑定页出现",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "手机号已绑定",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "确认手机号绑定页打开。",
                },
                {
                    "step_name": "校验更换手机号码按钮",
                    "step_type": "assert_exists",
                    "selector_type": "text",
                    "selector_value": "更换手机号码",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "确认更换入口存在。",
                },
            ],
        },
        {
            "key": "xianyu_leyuan_real_name_info_page",
            "name": "仙遇-账号管理-实名信息页",
            "summary": "覆盖实名信息入口后的只读页面，整理不可修改提示、实名姓名和证件号展示。",
            "ui_elements": [
                {
                    "page": "实名信息页",
                    "label": "页面标题",
                    "resource_id": "com.xianyui.qs.cn:id/tv_title",
                    "text": "实名信息",
                    "class_name": "android.widget.TextView",
                    "kind": "text",
                },
                {
                    "page": "实名信息页",
                    "label": "返回",
                    "resource_id": "com.xianyui.qs.cn:id/iv_back_view",
                    "text": "",
                    "class_name": "android.widget.ImageView",
                    "kind": "button",
                },
                {
                    "page": "实名信息页",
                    "label": "刷新",
                    "resource_id": "com.xianyui.qs.cn:id/iv_refresh_view",
                    "text": "",
                    "class_name": "android.widget.ImageView",
                    "kind": "button",
                },
                {
                    "page": "实名信息页",
                    "label": "关闭",
                    "resource_id": "com.xianyui.qs.cn:id/iv_close_view",
                    "text": "",
                    "class_name": "android.widget.ImageView",
                    "kind": "button",
                },
                {
                    "page": "实名信息页",
                    "label": "实名状态提示",
                    "resource_id": "",
                    "text": "亲爱的玩家，已进行实名认证，不可修改。",
                    "class_name": "android.widget.TextView",
                    "kind": "text",
                },
                {
                    "page": "实名信息页",
                    "label": "姓名",
                    "resource_id": "",
                    "text": "张**",
                    "class_name": "android.widget.TextView",
                    "kind": "text",
                },
                {
                    "page": "实名信息页",
                    "label": "证件号",
                    "resource_id": "",
                    "text": "441************519",
                    "class_name": "android.widget.TextView",
                    "kind": "text",
                },
                {
                    "page": "实名信息页",
                    "label": "联系客服中心",
                    "resource_id": "",
                    "text": "如有问题请联系客服中心",
                    "class_name": "android.widget.TextView",
                    "kind": "link",
                },
            ],
            "template_sections": [
                {
                    "title": "实名展示",
                    "summary": "页面是只读实名信息页，先确认不可修改提示和脱敏姓名、证件号是否正常显示。",
                    "goal": "实名信息完整展示。",
                    "controls": ["实名状态提示", "姓名", "证件号"],
                    "steps": ["点击实名信息", "校验实名信息页出现"],
                },
                {
                    "title": "客服入口",
                    "summary": "页面提供联系客服中心的跳转链接，适合后续补充客服分支。",
                    "goal": "客服入口可被识别。",
                    "controls": ["如有问题请联系客服中心"],
                    "steps": ["校验联系客服中心入口"],
                },
                {
                    "title": "返回恢复",
                    "summary": "保留返回、刷新和关闭，确保只读页也能快速回到账号管理页。",
                    "goal": "实名信息页可安全回退。",
                    "controls": ["返回", "刷新", "关闭"],
                    "steps": ["点击返回", "返回账号管理页"],
                },
            ],
            "steps": [
                {
                    "step_name": "点击实名信息",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "实名信息",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "从账号管理页进入实名信息页。",
                },
                {
                    "step_name": "校验实名信息页出现",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "实名信息",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "确认实名信息页打开。",
                },
                {
                    "step_name": "校验实名状态提示",
                    "step_type": "assert_exists",
                    "selector_type": "text",
                    "selector_value": "亲爱的玩家，已进行实名认证，不可修改。",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "确认只读提示可见。",
                },
                {
                    "step_name": "校验联系客服中心入口",
                    "step_type": "assert_exists",
                    "selector_type": "text",
                    "selector_value": "如有问题请联系客服中心",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "确认客服入口可见。",
                },
            ],
        },
        {
            "key": "xianyu_leyuan_third_party_sdk_directory_page",
            "name": "仙遇-账号管理-第三方SDK目录页",
            "summary": "覆盖第三方SDK目录页，整理已暴露的SDK列表、隐私链接和底部确认按钮。",
            "ui_elements": [
                {
                    "page": "第三方SDK目录页",
                    "label": "页面标题",
                    "resource_id": "com.xianyui.qs.cn:id/tv_title",
                    "text": "第三方SDK目录",
                    "class_name": "android.widget.TextView",
                    "kind": "text",
                },
                {
                    "page": "第三方SDK目录页",
                    "label": "返回",
                    "resource_id": "com.xianyui.qs.cn:id/iv_back_view",
                    "text": "",
                    "class_name": "android.widget.ImageView",
                    "kind": "button",
                },
                {
                    "page": "第三方SDK目录页",
                    "label": "刷新",
                    "resource_id": "com.xianyui.qs.cn:id/iv_refresh_view",
                    "text": "",
                    "class_name": "android.widget.ImageView",
                    "kind": "button",
                },
                {
                    "page": "第三方SDK目录页",
                    "label": "关闭",
                    "resource_id": "com.xianyui.qs.cn:id/iv_close_view",
                    "text": "",
                    "class_name": "android.widget.ImageView",
                    "kind": "button",
                },
                {
                    "page": "第三方SDK目录页",
                    "label": "广点通SDK",
                    "resource_id": "",
                    "text": "广点通SDK",
                    "class_name": "android.widget.TextView",
                    "kind": "text",
                },
                {
                    "page": "第三方SDK目录页",
                    "label": "快手SDK",
                    "resource_id": "",
                    "text": "快手SDK",
                    "class_name": "android.widget.TextView",
                    "kind": "text",
                },
                {
                    "page": "第三方SDK目录页",
                    "label": "百度SDK",
                    "resource_id": "",
                    "text": "百度SDK",
                    "class_name": "android.widget.TextView",
                    "kind": "text",
                },
                {
                    "page": "第三方SDK目录页",
                    "label": "头条SDK",
                    "resource_id": "",
                    "text": "头条SDK（字节增长营销SDK）",
                    "class_name": "android.widget.TextView",
                    "kind": "text",
                },
                {
                    "page": "第三方SDK目录页",
                    "label": "QuickSDK",
                    "resource_id": "",
                    "text": "QuickSDK",
                    "class_name": "android.widget.TextView",
                    "kind": "text",
                },
                {
                    "page": "第三方SDK目录页",
                    "label": "确认",
                    "resource_id": "",
                    "text": "确认",
                    "class_name": "android.widget.Button",
                    "kind": "button",
                },
            ],
            "template_sections": [
                {
                    "title": "SDK 列表",
                    "summary": "页面展示已接入的第三方 SDK 名称和用途说明，适合作为合规核对页。",
                    "goal": "第三方 SDK 名录可见。",
                    "controls": ["广点通SDK", "快手SDK", "百度SDK", "头条SDK", "QuickSDK"],
                    "steps": ["点击第三方SDK目录", "校验目录页出现"],
                },
                {
                    "title": "滚动查看",
                    "summary": "目录页内容较长，后续脚本可继续补滚动查看和逐项核对。",
                    "goal": "可继续向下浏览更多内容。",
                    "controls": ["滚动区域"],
                    "steps": ["向下滚动查看更多SDK"],
                },
                {
                    "title": "确认返回",
                    "summary": "页面底部带确认按钮，便于测试结束后返回账号管理页。",
                    "goal": "目录页可安全退出。",
                    "controls": ["确认", "返回"],
                    "steps": ["点击确认", "返回账号管理页"],
                },
            ],
            "steps": [
                {
                    "step_name": "点击第三方SDK目录",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "第三方SDK目录",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "从账号管理页进入第三方SDK目录页。",
                },
                {
                    "step_name": "校验目录页出现",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "第三方SDK目录",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "确认目录页标题和已展示内容可见。",
                },
                {
                    "step_name": "校验目录页SDK列表",
                    "step_type": "assert_exists",
                    "selector_type": "text",
                    "selector_value": "广点通SDK",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "确认 SDK 列表项开始展示。",
                },
                {
                    "step_name": "校验确认按钮",
                    "step_type": "assert_exists",
                    "selector_type": "text",
                    "selector_value": "确认",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "确认页底确认按钮存在。",
                },
            ],
        },
        {
            "key": "xianyu_leyuan_in_game_sdk_floating_panel",
            "name": "仙遇-游戏内 SDK 悬浮窗面板",
            "summary": "覆盖游戏进入后左侧悬浮窗入口、用户中心面板、账号切换与协议入口，适合验证游戏内 SDK 功能页是否可正常打开。",
            "ui_elements": floating_panel_elements,
            "template_sections": [
                {
                    "title": "悬浮入口打开",
                    "summary": "先确认游戏内左侧悬浮窗入口可点击，并能正确弹出用户中心面板。",
                    "goal": "从游戏主界面进入 SDK 功能页。",
                    "controls": ["左侧悬浮入口", "关闭弹窗"],
                    "steps": ["等待游戏主界面稳定", "点击左侧悬浮窗入口", "校验用户中心面板出现"],
                },
                {
                    "title": "账号分支",
                    "summary": "账号相关分支以切换账号为主，同时检查账号管理入口是否可打开。",
                    "goal": "账号切换和账号管理都能正常进入。",
                    "controls": ["切换账号", "账号管理"],
                    "steps": ["点击切换账号", "校验返回登录入口或二次确认弹窗出现", "返回用户中心面板", "点击账号管理", "校验账号管理页出现"],
                },
                {
                    "title": "客服与订单分支",
                    "summary": "客服、订单列表、加速属于功能性入口，适合分别验证是否能进入对应页面。",
                    "goal": "客服、订单列表和加速入口都可单独复现。",
                    "controls": ["客服", "订单列表", "加速"],
                    "steps": ["点击客服", "校验客服弹窗或客服页面出现", "返回用户中心面板", "点击订单列表", "校验订单列表页或订单弹窗出现", "返回用户中心面板", "点击加速", "校验加速状态或加速页出现"],
                },
                {
                    "title": "协议与隐私分支",
                    "summary": "协议、隐私类链接可打开，便于项目按需接入合规跳转。",
                    "goal": "协议与隐私入口保持可访问，点击后应出现对应协议页或 WebView。",
                    "controls": ["用户协议", "隐私政策"],
                    "steps": ["点击用户协议", "校验协议页或 WebView 出现", "返回用户中心面板", "点击隐私政策", "校验隐私页或 WebView 出现", "返回游戏主界面"],
                },
                {
                    "title": "关闭与回退",
                    "summary": "补充关闭弹窗与回到游戏主界面的稳定性检查。",
                    "goal": "关闭用户中心后能回到游戏主界面继续操作。",
                    "controls": ["关闭弹窗", "左侧悬浮入口"],
                    "steps": ["点击关闭弹窗", "确认回到游戏主界面", "再次点击悬浮入口复现"],
                },
            ],
            "steps": [
                {
                    "step_name": "等待游戏主界面稳定",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "任务",
                    "wait_timeout_sec": 120,
                    "capture_on_success": True,
                    "remark": "以游戏主界面上的任务入口作为稳定信号。",
                },
                {
                    "step_name": "打开并确认用户中心",
                    "step_type": "open_xianyu_user_center",
                    "selector_type": "image",
                    "selector_value": "xianyu/xianyu_user_center_title.png",
                    "wait_timeout_sec": 10,
                    "retry_times": 2,
                    "capture_on_success": True,
                    "remark": "每轮先定位并点击悬浮入口，确认用户中心未出现时再点击一次；最多 3 轮，并保存每轮截图。",
                },
                {
                    "step_name": "点击切换账号",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "切换账号",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "进入账号切换/重新登录入口。",
                },
                {
                    "step_name": "校验切换账号弹窗出现",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "账号",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "切换账号后通常会回到账号选择或登录弹窗。",
                },
                {
                    "step_name": "返回用户中心面板",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "用户中心",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "如果切换账号进入了新页面，可通过返回或关闭再次回到用户中心。",
                },
                {
                    "step_name": "点击账号管理",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "账号管理",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "验证账号管理入口。",
                },
                {
                    "step_name": "校验账号管理页出现",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "账号管理",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "账号管理页或弹窗出现后再返回用户中心。",
                },
                {
                    "step_name": "返回用户中心面板",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "用户中心",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "回到用户中心继续测试其他入口。",
                },
                {
                    "step_name": "点击客服",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "客服",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "验证客服入口。",
                },
                {
                    "step_name": "校验客服弹窗出现",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "客服",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "客服通常会打开新的对话框或 Web 页。",
                },
                {
                    "step_name": "返回用户中心面板",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "用户中心",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "关闭客服页后返回用户中心。",
                },
                {
                    "step_name": "点击订单列表",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "订单列表",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "验证订单入口。",
                },
                {
                    "step_name": "校验订单列表页出现",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "订单列表",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "订单页或弹窗出现后再返回用户中心。",
                },
                {
                    "step_name": "返回用户中心面板",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "用户中心",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "继续验证加速入口。",
                },
                {
                    "step_name": "点击加速",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "加速",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "验证加速功能入口。",
                },
                {
                    "step_name": "校验加速页出现",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "加速",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "加速页面或弹窗出现后结束该分支。",
                },
                {
                    "step_name": "点击用户协议",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "用户协议",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "验证用户中心协议入口。",
                },
                {
                    "step_name": "校验协议页出现",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "用户协议",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "协议页或者 WebView 页面出现后可继续返回。",
                },
                {
                    "step_name": "返回用户中心面板",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "用户中心",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "返回用户中心后继续测试隐私入口。",
                },
                {
                    "step_name": "点击隐私政策",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "隐私政策",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "验证用户中心隐私入口。",
                },
                {
                    "step_name": "校验隐私页出现",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "隐私政策",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "隐私页或 WebView 出现后返回游戏主界面。",
                },
                {
                    "step_name": "点击关闭弹窗",
                    "step_type": "tap_image",
                    "selector_type": "image",
                    "selector_value": "xianyu/xianyu_user_center_close.png",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "通过右上角关闭按钮模板退出用户中心并回到游戏主界面。",
                },
                {
                    "step_name": "保留悬浮窗功能页截图",
                    "step_type": "screenshot",
                    "selector_type": "none",
                    "selector_value": "",
                    "wait_timeout_sec": 5,
                    "capture_on_success": True,
                    "remark": "记录游戏内 SDK 功能页，便于后续对比样式和功能入口。",
                },
            ],
        },
        {
            "key": "xianyu_leyuan_sdk_login_standard_template",
            "name": "仙遇-乐享元游 SDK 登录标准模板",
            "summary": "把启动协议、账号登录、协议勾选和异常校验整理成可直接复用的标准模板，适合其他项目按控件映射快速改造。",
            "ui_elements": start_elements + login_elements,
            "template_sections": _sdk_login_standard_template_sections(),
            "steps": _switch_account_steps()
            + [
                {
                    "step_name": "输入测试账号",
                    "step_type": "input_text",
                    "selector_type": "text",
                    "selector_value": "请输入账号",
                    "input_value": "zsr005",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "标准模板默认账号位，可替换为项目自己的测试账号。",
                },
                {
                    "step_name": "输入测试密码",
                    "step_type": "input_text",
                    "selector_type": "text",
                    "selector_value": "请输入密码6-22位",
                    "input_value": "123456",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "标准模板默认密码位，可替换为项目自己的测试密码。",
                },
                {
                    "step_name": "勾选登录协议圆圈",
                    "step_type": "tap_left_of_text",
                    "selector_type": "text",
                    "selector_value": "我已详细阅读并同意",
                    "input_value": "26",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "兼容无文字复选框的协议勾选方式。",
                },
                {
                    "step_name": "点击登录游戏",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "登录游戏",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "提交账号密码并触发进入游戏主流程。",
                },
                {
                    "step_name": "等待进入游戏界面",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "公告",
                    "wait_timeout_sec": 90,
                    "capture_on_success": True,
                    "remark": "进入游戏后通常会先出现公告或加载完成后的首屏。",
                },
                {
                    "step_name": "保留进入游戏截图",
                    "step_type": "screenshot",
                    "selector_type": "none",
                    "selector_value": "",
                    "wait_timeout_sec": 5,
                    "capture_on_success": True,
                    "remark": "标准模板的成功终点，便于后续复用比对。",
                },
                {
                    "step_name": "输入特殊字符账号",
                    "step_type": "input_text",
                    "selector_type": "text",
                    "selector_value": "请输入账号",
                    "input_value": "zsr005!@#",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "覆盖账号输入中的特殊字符校验。",
                },
                {
                    "step_name": "输入过短密码",
                    "step_type": "input_text",
                    "selector_type": "text",
                    "selector_value": "请输入密码6-22位",
                    "input_value": "12",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "覆盖密码长度下限校验。",
                },
                {
                    "step_name": "未勾选协议直接点击登录",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "登录游戏",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "用于验证协议强制勾选场景。",
                },
                {
                    "step_name": "校验仍停留在账号登录页",
                    "step_type": "wait_text",
                    "selector_type": "text",
                    "selector_value": "忘记密码",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "如果协议未勾选，提交后应保持在登录页。",
                },
                {
                    "step_name": "保留异常输入结果截图",
                    "step_type": "screenshot",
                    "selector_type": "none",
                    "selector_value": "",
                    "wait_timeout_sec": 5,
                    "capture_on_success": True,
                    "remark": "异常案例截图，作为后续项目调优的参考。",
                },
            ],
        },
        {
            "key": "xianyu_leyuan_sdk_surface_audit",
            "name": "仙遇-乐享元游 SDK 界面巡检",
            "summary": "覆盖启动协议、资源加载后的手机号登录页元素是否正常展示，适合先做控件冒烟检查。",
            "ui_elements": start_elements + login_elements,
            "steps": _launch_steps()
            + [
                {
                    "step_name": "校验手机号输入框提示",
                    "step_type": "assert_exists",
                    "selector_type": "text",
                    "selector_value": "输入手机号",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "确认手机号输入框占位文案存在。",
                },
                {
                    "step_name": "校验本机号码入口",
                    "step_type": "assert_exists",
                    "selector_type": "text",
                    "selector_value": "本机号码",
                    "wait_timeout_sec": 15,
                    "capture_on_success": True,
                    "remark": "确认快捷登录辅助入口存在。",
                },
                {
                    "step_name": "校验账号登录入口",
                    "step_type": "assert_exists",
                    "selector_type": "text",
                    "selector_value": "账号登录",
                    "wait_timeout_sec": 15,
                    "capture_on_success": True,
                    "remark": "确认可以切换到账号密码登录模式。",
                },
                {
                    "step_name": "校验登录游戏按钮",
                    "step_type": "assert_exists",
                    "selector_type": "text",
                    "selector_value": "登录游戏",
                    "wait_timeout_sec": 15,
                    "capture_on_success": True,
                    "remark": "确认主提交按钮已经出现。",
                },
                {
                    "step_name": "保留 SDK 手机号登录页截图",
                    "step_type": "screenshot",
                    "selector_type": "none",
                    "selector_value": "",
                    "wait_timeout_sec": 5,
                    "capture_on_success": True,
                    "remark": "沉淀默认 SDK 登录页截图。",
                },
            ],
        },
        {
            "key": "xianyu_leyuan_switch_account_login",
            "name": "仙遇-切换账号密码登录",
            "summary": "覆盖从手机号登录页切换到账号密码登录页，并校验忘记密码等关键入口。",
            "ui_elements": login_elements,
            "steps": _switch_account_steps(),
        },
        {
            "key": "xianyu_leyuan_account_login",
            "name": "仙遇-乐享元游 SDK 账号登录",
            "summary": "覆盖启动协议、资源加载、账号登录、协议勾选与进入游戏界面。",
            "ui_elements": start_elements + login_elements,
            "steps": _switch_account_steps() + _sdk_account_password_steps(),
        },
        {
            "key": "xianyu_leyuan_forgot_password_entry",
            "name": "仙遇-忘记密码入口检查",
            "summary": "覆盖切到账号登录页后，忘记密码入口是否存在并可点击留痕。",
            "ui_elements": login_elements,
            "steps": _switch_account_steps()
            + [
                {
                    "step_name": "点击忘记密码入口",
                    "step_type": "tap_text",
                    "selector_type": "text",
                    "selector_value": "忘记密码",
                    "wait_timeout_sec": 15,
                    "capture_on_success": True,
                    "capture_on_failure": True,
                    "continue_on_failure": True,
                    "remark": "有些 SDK 会拉起 Web 页或二级弹窗，这里优先记录点击结果。",
                },
                {
                    "step_name": "保留忘记密码页截图",
                    "step_type": "screenshot",
                    "selector_type": "none",
                    "selector_value": "",
                    "wait_timeout_sec": 5,
                    "capture_on_success": True,
                    "remark": "无论是否成功跳转，都保留当前画面便于人工复核。",
                },
            ],
        },
        {
            "key": "xianyu_leyuan_protocol_required_guard",
            "name": "仙遇-账号登录协议勾选校验",
            "summary": "覆盖未勾选协议直接点登录时，是否仍停留在账号登录页，避免 SDK 放过必选协议。",
            "ui_elements": login_elements,
            "steps": _switch_account_steps()
            + _sdk_account_password_steps(
                account_value="zsr005",
                password_value="123456",
                include_checkbox=False,
                verify_entry=False,
            )
            + [
                {
                    "step_name": "校验仍停留在账号登录页",
                    "step_type": "assert_image_exists",
                    "selector_type": "image",
                    "selector_value": "xianyu/sdk_username_field.png",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "若协议必选，提交后应仍停留在账号登录页。",
                },
                {
                    "step_name": "保留协议未勾选结果截图",
                    "step_type": "screenshot",
                    "selector_type": "none",
                    "selector_value": "",
                    "wait_timeout_sec": 5,
                    "capture_on_success": True,
                    "remark": "沉淀协议未勾选时的阻断画面。",
                },
            ],
        },
        {
            "key": "xianyu_leyuan_invalid_input_guard",
            "name": "仙遇-账号密码异常输入校验",
            "summary": "覆盖账号特殊字符、密码过短等异常输入后，登录页是否仍保持可见，用于补基础输入校验。",
            "ui_elements": login_elements,
            "steps": _switch_account_steps()
            + _sdk_account_password_steps(
                account_value="zsr005!@#",
                password_value="12",
                include_checkbox=True,
                verify_entry=False,
            )
            + [
                {
                    "step_name": "校验账号页仍可见",
                    "step_type": "assert_image_exists",
                    "selector_type": "image",
                    "selector_value": "xianyu/sdk_username_field.png",
                    "wait_timeout_sec": 20,
                    "capture_on_success": True,
                    "remark": "当前框架先以未进入游戏、仍留在表单页作为基础校验信号。",
                },
                {
                    "step_name": "保留异常输入结果截图",
                    "step_type": "screenshot",
                    "selector_type": "none",
                    "selector_value": "",
                    "wait_timeout_sec": 5,
                    "capture_on_success": True,
                    "remark": "后续如补 toast 或 OCR 识别，可继续加强这类输入校验。",
                },
            ],
        },
    ]
