"""baseline schema

Revision ID: 69b8dc6ad11d
Revises: 
Create Date: 2026-06-25 10:36:44.313825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b8dc6ad11d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.alter_column('trigger_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'manual'"))
        batch_op.create_foreign_key(
            'fk_executions_trigger_user_id_users',
            'users',
            ['trigger_user_id'],
            ['id'],
            ondelete='SET NULL',
        )

    with op.batch_alter_table('scenario_executions', schema=None) as batch_op:
        batch_op.alter_column('trigger_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'manual'"))
        batch_op.create_foreign_key(
            'fk_scenario_executions_trigger_user_id_users',
            'users',
            ['trigger_user_id'],
            ['id'],
            ondelete='SET NULL',
        )

    with op.batch_alter_table('ui_automation_runs', schema=None) as batch_op:
        batch_op.alter_column('trigger_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'manual'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ui_automation_runs', schema=None) as batch_op:
        batch_op.alter_column('trigger_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'manual'"))

    with op.batch_alter_table('scenario_executions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scenario_executions_trigger_user_id_users', type_='foreignkey')
        batch_op.alter_column('trigger_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'manual'"))

    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_executions_trigger_user_id_users', type_='foreignkey')
        batch_op.alter_column('trigger_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'manual'"))

    # ### end Alembic commands ###
