"""add android ui automation models

Revision ID: e370cba83ac6
Revises: 69b8dc6ad11d
Create Date: 2026-07-07 10:55:06.911621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e370cba83ac6'
down_revision = '69b8dc6ad11d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('android_ui_test_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('package_key', sa.String(length=100), nullable=False),
    sa.Column('package_name', sa.String(length=200), nullable=False),
    sa.Column('apk_url', sa.Text(), nullable=False),
    sa.Column('channel_tag', sa.String(length=100), nullable=False),
    sa.Column('device_serial', sa.String(length=120), nullable=False),
    sa.Column('install_timeout_sec', sa.Integer(), nullable=False),
    sa.Column('launch_wait_sec', sa.Integer(), nullable=False),
    sa.Column('auto_uninstall', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'package_key', name='uq_android_ui_task_project_package_key')
    )
    op.create_table('android_ui_test_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('execution_no', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('download_status', sa.String(length=30), nullable=False),
    sa.Column('download_path', sa.String(length=500), nullable=False),
    sa.Column('download_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('aapt_status', sa.String(length=30), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('launchable_activity', sa.String(length=255), nullable=False),
    sa.Column('install_status', sa.String(length=30), nullable=False),
    sa.Column('launch_status', sa.String(length=30), nullable=False),
    sa.Column('crash_status', sa.String(length=30), nullable=False),
    sa.Column('pid', sa.String(length=50), nullable=False),
    sa.Column('current_focus', sa.Text(), nullable=False),
    sa.Column('device_serial', sa.String(length=120), nullable=False),
    sa.Column('device_name', sa.String(length=200), nullable=False),
    sa.Column('screenshot_path', sa.String(length=500), nullable=False),
    sa.Column('log_path', sa.String(length=500), nullable=False),
    sa.Column('error_type', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['android_ui_test_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('android_ui_test_runs')
    op.drop_table('android_ui_test_tasks')
    # ### end Alembic commands ###
