<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { CloudServerOutlined, EditOutlined, PlusOutlined, SearchOutlined } from '@ant-design/icons-vue'
import { message } from 'ant-design-vue'
import { usePlatformStore } from '../stores/platform'
import type { Environment } from '../types'

type EnvironmentForm = { projectId: number | undefined; name: string; baseUrl: string; description: string; isActive: boolean; headers: string; variables: string }
const platform = usePlatformStore()
const keyword = ref('')
const drawerOpen = ref(false)
const editingId = ref<number>()
const submitting = ref(false)
const form = ref<EnvironmentForm>({ projectId: undefined, name: '', baseUrl: '', description: '', isActive: true, headers: '{}', variables: '{}' })
const list = computed(() => platform.environments.filter((item) => `${item.name}${item.project}${item.baseUrl}${item.description}`.toLowerCase().includes(keyword.value.toLowerCase())))
const columns = [{ title: '环境', dataIndex: 'name', key: 'name' }, { title: '项目', dataIndex: 'project', key: 'project', width: 170 }, { title: 'Base URL', dataIndex: 'baseUrl', key: 'baseUrl' }, { title: '状态', dataIndex: 'isActive', key: 'isActive', width: 100 }, { title: '更新', dataIndex: 'updatedAt', key: 'updatedAt', width: 180 }, { title: '操作', key: 'action', width: 140 }]
onMounted(async () => { try { await platform.loadEnvironments() } catch { message.error('环境数据加载失败，请稍后重试。') } })
function reset() { form.value = { projectId: platform.activeProjectId ?? platform.projects[0]?.id, name: '', baseUrl: '', description: '', isActive: true, headers: '{}', variables: '{}' } }
function openCreate() { editingId.value = undefined; reset(); drawerOpen.value = true }
function openEdit(item: Environment) { editingId.value = item.id; form.value = { projectId: item.projectId, name: item.name, baseUrl: item.baseUrl, description: item.description, isActive: item.isActive, headers: JSON.stringify(item.headers, null, 2), variables: JSON.stringify(item.variables, null, 2) }; drawerOpen.value = true }
function parseObject(text: string, field: string) { try { const value = JSON.parse(text); if (!value || Array.isArray(value) || typeof value !== 'object') throw new Error(); return value as Record<string, string> } catch { message.error(`${field} 必须是 JSON 对象。`); return undefined } }
async function save() { const headers = parseObject(form.value.headers, '请求头'); const variables = parseObject(form.value.variables, '环境变量'); if (!headers || !variables) return; submitting.value = true; try { if (editingId.value) await platform.updateEnvironment(editingId.value, { name: form.value.name, baseUrl: form.value.baseUrl, description: form.value.description, isActive: form.value.isActive, headers, variables }); else if (form.value.projectId) await platform.addEnvironment({ projectId: form.value.projectId, name: form.value.name, baseUrl: form.value.baseUrl, description: form.value.description, isActive: form.value.isActive, headers, variables }); drawerOpen.value = false; message.success(editingId.value ? '环境已更新。' : '环境已创建。') } catch { message.error('保存环境失败，请检查权限和输入内容。') } finally { submitting.value = false } }
async function remove(item: Environment) { try { await platform.removeEnvironment(item.id); message.success('环境已删除。') } catch { message.error('删除环境失败，请稍后重试。') } }
</script>

<template>
  <section class="qa-panel p-5"><div class="flex flex-col gap-4 md:flex-row"><a-input v-model:value="keyword" class="flex-1" size="large" allow-clear placeholder="搜索环境、项目或 Base URL"><template #prefix><SearchOutlined class="text-slate-400" /></template></a-input><a-button type="primary" size="large" @click="openCreate"><PlusOutlined />新建环境</a-button></div></section>
  <section class="qa-panel mt-6 overflow-hidden"><div class="flex items-center justify-between p-6"><div><h2 class="section-title">可用环境</h2><p class="mb-0 mt-1 text-sm text-slate-400">共 {{ list.length }} 个环境，执行时仅可选择已启用项。</p></div><span class="rounded-lg bg-blue-50 px-3 py-1.5 text-xs text-brand"><CloudServerOutlined class="mr-1" />运行入口</span></div><a-table :data-source="list" :columns="columns" :pagination="{ pageSize: 8, showSizeChanger: false }" :scroll="{ x: 940 }" row-key="id" class="px-3"><template #bodyCell="{ column, record }"><template v-if="column.key === 'name'"><b class="text-ink">{{ record.name }}</b><small class="mt-1 block text-xs text-slate-400">{{ record.description || '未填写描述' }}</small></template><template v-else-if="column.key === 'isActive'"><a-tag :color="record.isActive ? 'success' : 'default'">{{ record.isActive ? '启用' : '停用' }}</a-tag></template><template v-else-if="column.key === 'updatedAt'">{{ record.updatedAt ? new Date(record.updatedAt).toLocaleString() : '-' }}</template><template v-else-if="column.key === 'action'"><a-button type="link" @click="openEdit(record)"><EditOutlined />编辑</a-button><a-popconfirm title="确认删除该环境吗？" ok-text="删除" cancel-text="取消" @confirm="remove(record)"><a-button danger type="link">删除</a-button></a-popconfirm></template></template></a-table></section>
  <a-drawer v-model:open="drawerOpen" :title="editingId ? '编辑环境' : '新建环境'" :width="'min(806px, 94vw)'" :footer-style="{ borderTop: '1px solid #e1ebfa' }"><p class="mb-6 text-sm text-slate-500">环境内变量会在执行时与项目变量合并，环境变量优先。</p><a-form layout="vertical" :model="form" @finish="save"><a-form-item label="所属项目" name="projectId" :rules="[{ required: true, message: '请选择所属项目' }]"><a-select v-model:value="form.projectId" size="large" :disabled="Boolean(editingId)"><a-select-option v-for="project in platform.projects" :key="project.id" :value="project.id">{{ project.name }}</a-select-option></a-select></a-form-item><div class="grid gap-x-4 md:grid-cols-2"><a-form-item label="环境名称" name="name" :rules="[{ required: true, message: '请输入环境名称' }]"><a-input v-model:value="form.name" size="large" placeholder="例如：预发布环境" /></a-form-item><a-form-item label="Base URL" name="baseUrl" :rules="[{ required: true, message: '请输入 Base URL' }]"><a-input v-model:value="form.baseUrl" size="large" placeholder="https://api.example.com" /></a-form-item></div><a-form-item label="描述"><a-textarea v-model:value="form.description" :rows="3" /></a-form-item><a-form-item label="状态"><a-switch v-model:checked="form.isActive" checked-children="启用" un-checked-children="停用" /></a-form-item><a-form-item label="通用请求头 JSON"><a-textarea v-model:value="form.headers" class="font-mono" :auto-size="{ minRows: 5, maxRows: 12 }" /></a-form-item><a-form-item label="环境变量 JSON"><a-textarea v-model:value="form.variables" class="font-mono" :auto-size="{ minRows: 5, maxRows: 12 }" /></a-form-item><div class="mt-8 flex justify-end gap-3"><a-button @click="drawerOpen = false">取消</a-button><a-button type="primary" :loading="submitting" html-type="submit">保存环境</a-button></div></a-form></a-drawer>
</template>

<style scoped>.eyebrow { @apply m-0 text-xs font-medium uppercase tracking-[.16em] text-brand; }.page-heading { @apply m-2 ml-0 text-[30px] font-display font-bold text-ink; }.section-title { @apply m-0 text-xl font-semibold text-ink; }</style>
