<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { CaretDownOutlined, CaretUpOutlined, DeleteOutlined, EditOutlined, PlayCircleOutlined, PlusOutlined, ThunderboltOutlined } from '@ant-design/icons-vue'
import { message } from 'ant-design-vue'
import CodeBlock from '../components/CodeBlock.vue'
import { platformApi } from '../services/platform'
import { usePlatformStore } from '../stores/platform'
import type { Scenario, ScenarioExecution, ScenarioStep } from '../types'

type ScenarioForm = { projectId: number | undefined; moduleId: number | null; name: string; description: string; status: 'active' | 'inactive'; tagsText: string }
type StepForm = { testcaseId: number | null; name: string; isEnabled: boolean; continueOnFailure: boolean; setupVariables: string; requestOverrides: string; extractOverrides: string; assertionOverrides: string }
const platform = usePlatformStore()
const keyword = ref('')
const editorOpen = ref(false)
const composerOpen = ref(false)
const runOpen = ref(false)
const historyOpen = ref(false)
const selected = ref<Scenario>()
const selectedExecution = ref<ScenarioExecution>()
const editingId = ref<number>()
const editingStepId = ref<number>()
const submitting = ref(false)
const scenarioForm = ref<ScenarioForm>({ projectId: undefined, moduleId: null, name: '', description: '', status: 'active', tagsText: '' })
const stepForm = ref<StepForm>({ testcaseId: null, name: '', isEnabled: true, continueOnFailure: false, setupVariables: '{}', requestOverrides: '{}', extractOverrides: '{}', assertionOverrides: '[]' })
const runForm = ref({ environmentId: undefined as number | undefined, persistExtracted: true, runtimeInjections: '{}' })
const list = computed(() => platform.scenarios.filter((item) => `${item.name}${item.description}${item.module ?? ''}${item.tags.join(' ')}`.toLowerCase().includes(keyword.value.toLowerCase())))
const moduleOptions = computed(() => platform.modules.filter((item) => item.projectId === scenarioForm.value.projectId))
const testcaseOptions = computed(() => platform.testcases.filter((item) => item.projectId === selected.value?.projectId))
const environmentOptions = computed(() => platform.environments.filter((item) => item.projectId === selected.value?.projectId && item.isActive))
const columns = [{ title: '场景', dataIndex: 'name', key: 'name' }, { title: '所属模块', dataIndex: 'module', key: 'module', width: 150 }, { title: '步骤', dataIndex: 'stepCount', key: 'stepCount', width: 90 }, { title: '状态', dataIndex: 'status', key: 'status', width: 100 }, { title: '更新', dataIndex: 'updatedAt', key: 'updatedAt', width: 180 }, { title: '操作', key: 'action', width: 200 }]
onMounted(async () => { try { await Promise.all([platform.loadScenarios(), platform.loadScenarioExecutions(), platform.loadModules(), platform.loadTestcases(), platform.loadEnvironments()]) } catch { message.error('场景数据加载失败，请稍后重试。') } })
function resetScenarioForm() { scenarioForm.value = { projectId: platform.activeProjectId ?? platform.projects[0]?.id, moduleId: null, name: '', description: '', status: 'active', tagsText: '' } }
function openCreate() { editingId.value = undefined; resetScenarioForm(); editorOpen.value = true }
function openEdit(item: Scenario) { editingId.value = item.id; scenarioForm.value = { projectId: item.projectId, moduleId: item.moduleId, name: item.name, description: item.description, status: item.status, tagsText: item.tags.join(', ') }; editorOpen.value = true }
function parseTags() { return scenarioForm.value.tagsText.split(',').map((item) => item.trim()).filter(Boolean) }
async function saveScenario() { if (!scenarioForm.value.projectId) return; submitting.value = true; try { if (editingId.value) await platform.updateScenario(editingId.value, { moduleId: scenarioForm.value.moduleId, name: scenarioForm.value.name, description: scenarioForm.value.description, status: scenarioForm.value.status, tags: parseTags() }); else await platform.addScenario({ projectId: scenarioForm.value.projectId, moduleId: scenarioForm.value.moduleId, name: scenarioForm.value.name, description: scenarioForm.value.description, status: scenarioForm.value.status, tags: parseTags() }); editorOpen.value = false; await platform.loadScenarios(); message.success('场景已保存。') } catch { message.error('保存场景失败，请检查项目、模块和名称。') } finally { submitting.value = false } }
async function removeScenario(item: Scenario) { try { await platform.removeScenario(item.id); message.success('场景已删除。') } catch { message.error('删除场景失败。') } }
async function openComposer(item: Scenario) { try { selected.value = await platformApi.scenario(item.id); composerOpen.value = true; resetStepForm() } catch { message.error('场景编排加载失败。') } }
function resetStepForm() { editingStepId.value = undefined; stepForm.value = { testcaseId: testcaseOptions.value[0]?.id ?? null, name: '', isEnabled: true, continueOnFailure: false, setupVariables: '{}', requestOverrides: '{}', extractOverrides: '{}', assertionOverrides: '[]' } }
function editStep(step: ScenarioStep) { editingStepId.value = step.id; stepForm.value = { testcaseId: step.testcaseId, name: step.name, isEnabled: step.isEnabled, continueOnFailure: step.continueOnFailure, setupVariables: JSON.stringify(step.setupVariables, null, 2), requestOverrides: JSON.stringify(step.requestOverrides, null, 2), extractOverrides: JSON.stringify(step.extractOverrides, null, 2), assertionOverrides: JSON.stringify(step.assertionOverrides, null, 2) } }
function parseJson(text: string, fallback: object | unknown[]) { try { const value = JSON.parse(text); if (!value || typeof value !== 'object') throw new Error(); return value } catch { message.error('步骤覆盖配置必须是有效 JSON。'); return fallback } }
async function saveStep() { if (!selected.value || !stepForm.value.testcaseId) return; const setupVariables = parseJson(stepForm.value.setupVariables, {}); const requestOverrides = parseJson(stepForm.value.requestOverrides, {}); const extractOverrides = parseJson(stepForm.value.extractOverrides, {}); const assertionOverrides = parseJson(stepForm.value.assertionOverrides, []); if (!setupVariables || !requestOverrides || !extractOverrides || !assertionOverrides) return; submitting.value = true; const payload = { testcaseId: stepForm.value.testcaseId, name: stepForm.value.name, isEnabled: stepForm.value.isEnabled, continueOnFailure: stepForm.value.continueOnFailure, setupVariables, requestOverrides, extractOverrides, assertionOverrides: Array.isArray(assertionOverrides) ? assertionOverrides : [] }; try { if (editingStepId.value) await platformApi.updateScenarioStep(editingStepId.value, payload); else await platformApi.createScenarioStep(selected.value.id, payload); selected.value = await platformApi.scenario(selected.value.id); await platform.loadScenarios(); resetStepForm(); message.success('步骤已保存。') } catch { message.error('保存步骤失败，请确认所选用例属于当前项目。') } finally { submitting.value = false } }
async function moveStep(step: ScenarioStep, direction: 'up' | 'down') { if (!selected.value) return; try { selected.value = await platformApi.moveScenarioStep(step.id, direction); await platform.loadScenarios() } catch { message.error('调整步骤顺序失败。') } }
async function removeStep(step: ScenarioStep) { if (!selected.value) return; try { await platformApi.deleteScenarioStep(step.id); selected.value = await platformApi.scenario(selected.value.id); await platform.loadScenarios() } catch { message.error('删除步骤失败。') } }
function openRun(item: Scenario) { selected.value = item; runForm.value = { environmentId: platform.environments.find((env) => env.projectId === item.projectId && env.isActive)?.id, persistExtracted: true, runtimeInjections: '{}' }; runOpen.value = true }
async function submitRun() { if (!selected.value || !runForm.value.environmentId) { message.warning('请选择执行环境。'); return } let runtimeInjections: Record<string, unknown>; try { runtimeInjections = JSON.parse(runForm.value.runtimeInjections) } catch { message.error('运行时变量必须是 JSON 对象。'); return } submitting.value = true; try { const execution = await platform.runScenario({ scenarioId: selected.value.id, environmentId: runForm.value.environmentId, persistExtracted: runForm.value.persistExtracted, runtimeInjections }); runOpen.value = false; message.success(`场景执行完成：${execution.passedSteps}/${execution.totalSteps} 步通过。`) } catch { message.error('场景执行失败，请检查环境、步骤和用例配置。') } finally { submitting.value = false } }
async function openHistory(item: ScenarioExecution) { try { selectedExecution.value = await platformApi.scenarioExecution(item.id); historyOpen.value = true } catch { message.error('场景执行明细加载失败。') } }
</script>

<template>
  <section class="qa-panel p-5"><div class="flex flex-col gap-4 md:flex-row"><a-input v-model:value="keyword" class="flex-1" size="large" allow-clear placeholder="搜索场景、模块或标签" /><a-button type="primary" size="large" @click="openCreate"><PlusOutlined />新建场景</a-button></div></section>
  <section class="qa-panel mt-6 overflow-hidden"><div class="flex items-center justify-between p-6"><div><h2 class="section-title">场景列表</h2><p class="mb-0 mt-1 text-sm text-slate-400">共 {{ list.length }} 个场景，步骤顺序由编排面板维护。</p></div><span class="rounded-lg bg-blue-50 px-3 py-1.5 text-xs text-brand"><ThunderboltOutlined class="mr-1" />链路执行</span></div><a-table :data-source="list" :columns="columns" :pagination="{ pageSize: 8, showSizeChanger: false }" :scroll="{ x: 1000 }" row-key="id" class="px-3"><template #bodyCell="{ column, record }"><template v-if="column.key === 'name'"><b class="text-ink">{{ record.name }}</b><div class="mt-1 flex gap-1"><a-tag v-for="tag in record.tags" :key="tag" class="!m-0">{{ tag }}</a-tag></div></template><template v-else-if="column.key === 'status'"><a-tag :color="record.status === 'active' ? 'success' : 'default'">{{ record.status === 'active' ? '启用' : '停用' }}</a-tag></template><template v-else-if="column.key === 'updatedAt'">{{ record.updatedAt ? new Date(record.updatedAt).toLocaleString() : '-' }}</template><template v-else-if="column.key === 'action'"><a-button type="link" @click="openComposer(record)">编排</a-button><a-button type="link" @click="openRun(record)"><PlayCircleOutlined />执行</a-button><a-button type="link" @click="openEdit(record)"><EditOutlined />编辑</a-button><a-popconfirm title="确认删除该场景及其步骤吗？" ok-text="删除" cancel-text="取消" @confirm="removeScenario(record)"><a-button danger type="link">删除</a-button></a-popconfirm></template></template></a-table></section>
  <section class="qa-panel mt-6 overflow-hidden"><div class="p-6"><h2 class="section-title">场景执行历史</h2><p class="mb-0 mt-1 text-sm text-slate-400">保留步骤级请求、响应、断言和提取结果。</p></div><a-table :data-source="platform.scenarioExecutions" :pagination="{ pageSize: 6, showSizeChanger: false }" row-key="id" class="px-3"><a-table-column title="场景" data-index="scenario" key="scenario" /><a-table-column title="环境" data-index="environment" key="environment" /><a-table-column title="状态" data-index="status" key="status"><template #default="{ record }"><a-tag :color="record.status === 'passed' ? 'success' : record.status === 'failed' ? 'error' : 'default'">{{ record.status }}</a-tag></template></a-table-column><a-table-column title="结果" key="result"><template #default="{ record }">{{ record.passedSteps }}/{{ record.totalSteps }} 步通过</template></a-table-column><a-table-column title="操作" key="action"><template #default="{ record }"><a-button type="link" @click="openHistory(record)">查看明细</a-button></template></a-table-column></a-table></section>
  <a-drawer v-model:open="editorOpen" :title="editingId ? '编辑场景' : '新建场景'" :width="'min(806px, 94vw)'" :footer-style="{ borderTop: '1px solid #e1ebfa' }"><a-form layout="vertical" :model="scenarioForm" @finish="saveScenario"><a-form-item label="所属项目" name="projectId" :rules="[{ required: true, message: '请选择所属项目' }]"><a-select v-model:value="scenarioForm.projectId" size="large" :disabled="Boolean(editingId)"><a-select-option v-for="project in platform.projects" :key="project.id" :value="project.id">{{ project.name }}</a-select-option></a-select></a-form-item><a-form-item label="所属模块"><a-select v-model:value="scenarioForm.moduleId" allow-clear size="large"><a-select-option v-for="module in moduleOptions" :key="module.id" :value="module.id">{{ module.name }}</a-select-option></a-select></a-form-item><a-form-item label="场景名称" name="name" :rules="[{ required: true, message: '请输入场景名称' }]"><a-input v-model:value="scenarioForm.name" size="large" /></a-form-item><a-form-item label="描述"><a-textarea v-model:value="scenarioForm.description" :rows="3" /></a-form-item><a-form-item label="标签"><a-input v-model:value="scenarioForm.tagsText" placeholder="用英文逗号分隔，例如：smoke, payment" /></a-form-item><a-form-item label="状态"><a-radio-group v-model:value="scenarioForm.status"><a-radio value="active">启用</a-radio><a-radio value="inactive">停用</a-radio></a-radio-group></a-form-item><div class="mt-8 flex justify-end gap-3"><a-button @click="editorOpen = false">取消</a-button><a-button type="primary" :loading="submitting" html-type="submit">保存场景</a-button></div></a-form></a-drawer>
  <a-drawer v-model:open="composerOpen" :title="`${selected?.name ?? ''} · 步骤编排`" :width="'min(806px, 94vw)'" :footer-style="{ borderTop: '1px solid #e1ebfa' }"><template v-if="selected"><div class="mb-6 space-y-3"><article v-for="step in selected.steps" :key="step.id" class="step-card"><div class="flex items-center justify-between gap-3"><div><b>{{ step.orderNo }}. {{ step.name || step.testcaseName }}</b><small class="mt-1 block text-slate-400">{{ step.testcaseName }} · {{ step.isEnabled ? '启用' : '停用' }} · {{ step.continueOnFailure ? '失败继续' : '失败中止' }}</small></div><div><a-button type="text" @click="moveStep(step, 'up')"><CaretUpOutlined /></a-button><a-button type="text" @click="moveStep(step, 'down')"><CaretDownOutlined /></a-button><a-button type="link" @click="editStep(step)">编辑</a-button><a-popconfirm title="确认删除此步骤吗？" @confirm="removeStep(step)"><a-button danger type="text"><DeleteOutlined /></a-button></a-popconfirm></div></div></article></div><a-divider>步骤配置</a-divider><a-form layout="vertical" :model="stepForm" @finish="saveStep"><a-form-item label="关联用例"><a-select v-model:value="stepForm.testcaseId" size="large"><a-select-option v-for="testcase in testcaseOptions" :key="testcase.id" :value="testcase.id">{{ testcase.module }} · {{ testcase.name }}</a-select-option></a-select></a-form-item><a-form-item label="步骤名称"><a-input v-model:value="stepForm.name" placeholder="留空时使用用例名称" /></a-form-item><div class="mb-5 flex gap-6"><a-checkbox v-model:checked="stepForm.isEnabled">启用步骤</a-checkbox><a-checkbox v-model:checked="stepForm.continueOnFailure">失败后继续执行</a-checkbox></div><a-collapse><a-collapse-panel key="overrides" header="高级覆盖配置"><a-form-item label="步骤变量注入 JSON"><a-textarea v-model:value="stepForm.setupVariables" class="font-mono" :rows="4" /></a-form-item><a-form-item label="请求覆盖 JSON"><a-textarea v-model:value="stepForm.requestOverrides" class="font-mono" :rows="4" /></a-form-item><a-form-item label="提取覆盖 JSON"><a-textarea v-model:value="stepForm.extractOverrides" class="font-mono" :rows="4" /></a-form-item><a-form-item label="断言覆盖 JSON"><a-textarea v-model:value="stepForm.assertionOverrides" class="font-mono" :rows="4" /></a-form-item></a-collapse-panel></a-collapse><div class="mt-6 flex justify-end gap-3"><a-button @click="resetStepForm">重置</a-button><a-button type="primary" :loading="submitting" html-type="submit">{{ editingStepId ? '更新步骤' : '添加步骤' }}</a-button></div></a-form></template></a-drawer>
  <a-drawer v-model:open="runOpen" :title="`${selected?.name ?? ''} · 执行配置`" :width="'min(806px, 94vw)'" :footer-style="{ borderTop: '1px solid #e1ebfa' }"><a-form layout="vertical" :model="runForm" @finish="submitRun"><a-form-item label="执行环境" name="environmentId" :rules="[{ required: true, message: '请选择执行环境' }]"><a-select v-model:value="runForm.environmentId" size="large"><a-select-option v-for="environment in environmentOptions" :key="environment.id" :value="environment.id">{{ environment.name }} · {{ environment.baseUrl }}</a-select-option></a-select></a-form-item><a-form-item label="运行时变量 JSON"><a-textarea v-model:value="runForm.runtimeInjections" class="font-mono" :rows="6" /></a-form-item><a-checkbox v-model:checked="runForm.persistExtracted">将提取变量回写至环境</a-checkbox><div class="mt-8 flex justify-end gap-3"><a-button @click="runOpen = false">取消</a-button><a-button type="primary" :loading="submitting" html-type="submit">开始执行</a-button></div></a-form></a-drawer>
  <a-drawer v-model:open="historyOpen" :title="`场景执行明细 · #${selectedExecution?.id ?? ''}`" :width="'min(806px, 94vw)'" :footer-style="{ borderTop: '1px solid #e1ebfa' }"><template v-if="selectedExecution"><a-collapse><a-collapse-panel v-for="item in selectedExecution.details" :key="item.id" :header="`${item.stepName} · ${item.status}`"><p v-if="item.errorMessage" class="text-red-500">{{ item.errorMessage }}</p><p class="font-medium text-ink">请求快照</p><CodeBlock :code="JSON.stringify(item.request, null, 2)" /><p class="mt-5 font-medium text-ink">响应快照</p><CodeBlock :code="JSON.stringify(item.response, null, 2)" /></a-collapse-panel></a-collapse></template></a-drawer>
</template>

<style scoped>.eyebrow { @apply m-0 text-xs font-medium uppercase tracking-[.16em] text-brand; }.page-heading { @apply m-2 ml-0 text-[30px] font-display font-bold text-ink; }.section-title { @apply m-0 text-xl font-semibold text-ink; }.step-card { @apply rounded-xl border border-line bg-slate-50 p-4; }</style>
