<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { KeyOutlined, PlusOutlined, SearchOutlined } from '@ant-design/icons-vue'
import { message } from 'ant-design-vue'
import { usePlatformStore } from '../stores/platform'
import type { Variable } from '../types'

type VariableForm = { projectId: number | undefined; environmentId: number | null; name: string; value: string; scope: 'project' | 'environment'; description: string }
const platform = usePlatformStore()
const keyword = ref('')
const drawerOpen = ref(false)
const editingId = ref<number>()
const submitting = ref(false)
const form = ref<VariableForm>({ projectId: undefined, environmentId: null, name: '', value: '', scope: 'project', description: '' })
const list = computed(() => platform.variables.filter((item) => `${item.name}${item.value}${item.project}${item.environment ?? ''}${item.description}`.toLowerCase().includes(keyword.value.toLowerCase())))
const environmentOptions = computed(() => platform.environments.filter((environment) => environment.projectId === form.value.projectId))
const columns = [{ title: '变量名', dataIndex: 'name', key: 'name' }, { title: '值', dataIndex: 'value', key: 'value' }, { title: '作用域', dataIndex: 'scope', key: 'scope', width: 120 }, { title: '关联环境', dataIndex: 'environment', key: 'environment', width: 150 }, { title: '更新', dataIndex: 'updatedAt', key: 'updatedAt', width: 180 }, { title: '操作', key: 'action', width: 120 }]
onMounted(async () => { try { await Promise.all([platform.loadVariables(), platform.loadEnvironments()]) } catch { message.error('变量数据加载失败，请稍后重试。') } })
function reset() { form.value = { projectId: platform.activeProjectId ?? platform.projects[0]?.id, environmentId: null, name: '', value: '', scope: 'project', description: '' } }
function openCreate() { editingId.value = undefined; reset(); drawerOpen.value = true }
function openEdit(item: Variable) { editingId.value = item.id; form.value = { projectId: item.projectId, environmentId: item.environmentId, name: item.name, value: item.value, scope: item.scope, description: item.description }; drawerOpen.value = true }
function changeScope() { if (form.value.scope === 'project') form.value.environmentId = null; else form.value.environmentId = environmentOptions.value[0]?.id ?? null }
async function save() { if (!form.value.projectId) return; submitting.value = true; try { if (editingId.value) await platform.updateVariable(editingId.value, { environmentId: form.value.scope === 'environment' ? form.value.environmentId : null, name: form.value.name, value: form.value.value, scope: form.value.scope, description: form.value.description }); else await platform.addVariable({ projectId: form.value.projectId, environmentId: form.value.scope === 'environment' ? form.value.environmentId : null, name: form.value.name, value: form.value.value, scope: form.value.scope, description: form.value.description }); drawerOpen.value = false; message.success(editingId.value ? '变量已更新。' : '变量已创建。') } catch { message.error('保存变量失败，请检查变量作用域和环境归属。') } finally { submitting.value = false } }
async function remove(item: Variable) { try { await platform.removeVariable(item.id); message.success('变量已删除。') } catch { message.error('删除变量失败，请稍后重试。') } }
</script>

<template>
  <section class="qa-panel p-5"><div class="flex flex-col gap-4 md:flex-row"><a-input v-model:value="keyword" class="flex-1" size="large" allow-clear placeholder="搜索变量名、变量值或描述"><template #prefix><SearchOutlined class="text-slate-400" /></template></a-input><a-button type="primary" size="large" @click="openCreate"><PlusOutlined />新建变量</a-button></div></section>
  <section class="qa-panel mt-6 overflow-hidden"><div class="flex items-center justify-between p-6"><div><h2 class="section-title">运行变量</h2><p class="mb-0 mt-1 text-sm text-slate-400">共 {{ list.length }} 条变量配置。</p></div><span class="rounded-lg bg-blue-50 px-3 py-1.5 text-xs text-brand"><KeyOutlined class="mr-1" />动态注入</span></div><a-table :data-source="list" :columns="columns" :pagination="{ pageSize: 10, showSizeChanger: false }" :scroll="{ x: 900 }" row-key="id" class="px-3"><template #bodyCell="{ column, record }"><template v-if="column.key === 'name'"><b class="font-mono text-ink">{{ record.name }}</b><small class="mt-1 block text-xs text-slate-400">{{ record.description || '未填写描述' }}</small></template><template v-else-if="column.key === 'value'"><span class="font-mono text-slate-600">{{ record.value }}</span></template><template v-else-if="column.key === 'scope'"><a-tag :color="record.scope === 'environment' ? 'blue' : 'default'">{{ record.scope === 'environment' ? '环境级' : '项目级' }}</a-tag></template><template v-else-if="column.key === 'updatedAt'">{{ record.updatedAt ? new Date(record.updatedAt).toLocaleString() : '-' }}</template><template v-else-if="column.key === 'action'"><a-button type="link" @click="openEdit(record)">编辑</a-button><a-popconfirm title="确认删除该变量吗？" ok-text="删除" cancel-text="取消" @confirm="remove(record)"><a-button danger type="link">删除</a-button></a-popconfirm></template></template></a-table></section>
  <a-drawer v-model:open="drawerOpen" :title="editingId ? '编辑变量' : '新建变量'" :width="'min(806px, 94vw)'" :footer-style="{ borderTop: '1px solid #e1ebfa' }"><p class="mb-6 text-sm text-slate-500">环境级变量会覆盖同名项目级变量；项目归属在编辑时不可变更。</p><a-form layout="vertical" :model="form" @finish="save"><a-form-item label="所属项目" name="projectId" :rules="[{ required: true, message: '请选择所属项目' }]"><a-select v-model:value="form.projectId" size="large" :disabled="Boolean(editingId)" @change="changeScope"><a-select-option v-for="project in platform.projects" :key="project.id" :value="project.id">{{ project.name }}</a-select-option></a-select></a-form-item><div class="grid gap-x-4 md:grid-cols-2"><a-form-item label="变量名称" name="name" :rules="[{ required: true, message: '请输入变量名称' }]"><a-input v-model:value="form.name" size="large" placeholder="例如：access_token" /></a-form-item><a-form-item label="变量值" name="value"><a-input v-model:value="form.value" size="large" /></a-form-item></div><a-form-item label="作用域"><a-radio-group v-model:value="form.scope" @change="changeScope"><a-radio value="project">项目级</a-radio><a-radio value="environment">环境级</a-radio></a-radio-group></a-form-item><a-form-item v-if="form.scope === 'environment'" label="关联环境" name="environmentId" :rules="[{ required: true, message: '请选择环境' }]"><a-select v-model:value="form.environmentId" size="large"><a-select-option v-for="environment in environmentOptions" :key="environment.id" :value="environment.id">{{ environment.name }}</a-select-option></a-select></a-form-item><a-form-item label="描述"><a-textarea v-model:value="form.description" :rows="4" /></a-form-item><div class="mt-8 flex justify-end gap-3"><a-button @click="drawerOpen = false">取消</a-button><a-button type="primary" :loading="submitting" html-type="submit">保存变量</a-button></div></a-form></a-drawer>
</template>

<style scoped>.eyebrow { @apply m-0 text-xs font-medium uppercase tracking-[.16em] text-brand; }.page-heading { @apply m-2 ml-0 text-[30px] font-display font-bold text-ink; }.section-title { @apply m-0 text-xl font-semibold text-ink; }</style>
